### ISSUE TITLE
track/map no longer works

### ISSUE THREAD

**Issue by jimklo** [samdutton/simpl#103]
Went to go reference your example here: https://simpl.info/track/map/ to find it no longer works in any browser.

I think there were some recent changes to the WebVTT API and it can no longer accept NaN as a cue time value.

**Comment by samdutton** [comment]
Seems to go wrong intermittently. Guess it's a timing issue (fine running locally).

Made some updates recently (to get rid of jQuery dependency) but guess I broke it :).

I'm pretty busy this week and next, but I'll try to take a look.

**Comment by samdutton** [comment]
Meant to update this issue — I fixed the code a while back. Please let me know if you still have problems.
