### ISSUE TITLE
Doesn't work on safari or IOS

### ISSUE THREAD

**Issue by nirbhaysingh1074** [samdutton/simpl#108]
Please help me.
Thank you

**Comment by samdutton** [comment]
With what :)?

**Comment by guywel** [comment]
Sorry Sam,

 

I must have done something wrong. I’m not used to work with Github…

Whatever I’ve sent, please ignore. 

 

I was looking for a script to scan documents from a mobile phone.

 

Kind regards,

 

Guy

 

Van: Sam Dutton [mailto:notifications@github.com] 
Verzonden: maandag 24 juli 2017 13:33
Aan: samdutton/simpl <simpl@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: Re: [samdutton/simpl] Doesn't work on safari or IOS (#108)

 

With what :)?

**Comment by samdutton** [comment]
No worries!
