### ISSUE TITLE
Doesn't work on safari or IOS

### ISSUE THREAD

**Issue by nirbhaysingh1074** [samdutton/simpl#109]
in **_simpl/mediarecorder/video-only_**
mediaRecorder is not working with safari and IOS.
Please give me suggestion.
Thank you

**Comment by samdutton** [comment]
The MediaRecorder API is [not supported by Safari](http://caniuse.com/#search=mediarecorder) and therefore not by Chrome on iOS. 

I don't know of any good alternatives :(.
