### ISSUE TITLE
 convert this blob video to mp4 or any other format(to upload on my server). 

### ISSUE THREAD

**Issue by Saqib92** [samdutton/simpl#110]
I want to convert this blob video to my server as my server receives mp4 or other format but not BLOB. 
So please add functionality to convert this blob into any other format (preferably MP4).

**Comment by fredr-juwai** [comment]
Please also add a functionality to automatically save the video to a specified local/remote folder and filename.

**Comment by samdutton** [comment]
Are you talking about [simpl.info/mediarecorder](https://simpl.info/mediarecorder)? If so, you can save a file (locally) by clicking the Download button. 

If you want to use MP4, you need to set the container and codecs — but, of course, that will only work on a platform that supports MediaRecorder and recording in MP4.

**Comment by greenm1nd3d** [comment]
Thank you for your response @samdutton but we don't want to click the Download button. We want to be able to save the video as soon as "Stop Recording" button is pressed. We don't want to trigger the "Save As" functionality of the browser. Thanks in advance.

**Comment by samdutton** [comment]
Hi @greenm1nd3d — if you want to save the video as soon as the Stop Recording button is pressed, just use the `download()` code in the handler for clicks from that button.

**Comment by Saqib92** [comment]
Thanks for your Response @samdutton , My issue has been resolved as i want to save that blob video to my server. I converted it into base64 and sent it to my server. Thanks again for this great repository.

**Comment by samdutton** [comment]
Cheers @Saqib92!

**Comment by vishnu-sagubandi** [comment]
> Thanks for your Response @samdutton , My issue has been resolved as i want to save that blob video to my server. I converted it into base64 and sent it to my server. Thanks again for this great repository.

Hey @Saqib92 . I was facing the issue with uploading blobs to my server. It will be great if u can plz share your code with me.

**Comment by Saqib92** [comment]
> > Thanks for your Response @samdutton , My issue has been resolved as i want to save that blob video to my server. I converted it into base64 and sent it to my server. Thanks again for this great repository.
> 
> Hey @Saqib92 . I was facing the same issue with uploading blobs to my server. It will be great if u can plz share your code with me.

the issue is way too old and I don't have that code any more. I can help if you shar you code.
