### ISSUE TITLE
Safari 11.0 not getting media showing black screen 

### ISSUE THREAD

**Issue by arun3528** [samdutton/simpl#112]
https://simpl.info/getusermedia/

Error: getUserMedia error: 
TypeError: Type error
createObjectURL
handleSuccess — main.js:27
promiseReactionJob

**Comment by samdutton** [comment]
Thanks for the heads up!

Fixed [here](https://github.com/samdutton/simpl/commit/5b8d5a5fd03fd265024e54da23b02426338822aa).

Let me know if you're still experiencing problems.

**Comment by OwenMelbz** [comment]
@samdutton Hey, we still only see black boxes on ios 11.3

![img_6f086d548293-1](https://user-images.githubusercontent.com/1094740/38431674-e1658b98-39bc-11e8-8264-e89df5790fcd.jpeg)

**Comment by samdutton** [comment]
I've added `playsinline` — does this fix it for you? I don't have an iOS device with 11.3 to hand. (Works in Safari on Mac.)

Does [webrtc.github.io/samples/src/content/getusermedia/gum](https://webrtc.github.io/samples/src/content/getusermedia/gum/) work for you? That's the canonical demo. Do any other demos work?

If none of the examples work, this seems like an iOS/Safari bug.
