### ISSUE TITLE
EventSource demo site not working

### ISSUE THREAD

**Issue by markus-walther-tutti** [samdutton/simpl#113]
https://simpl.info/eventsource/ fails to show activity due to `Failed to load https://sse.now.sh/: Redirect from 'https://sse.now.sh/' to 'https://zeit.co/hemanth/sse-now/vhtqsczurm?redirect=1' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://simpl.info' is therefore not allowed access.`

**Comment by samdutton** [comment]
Thanks for the heads-up!  

@hemanth: fancy doing a PR :)?

**Comment by hemanth** [comment]
No clue in the logs, it was working fine the last time I checked it, will work with now's team and get back.

**Comment by hemanth** [comment]
It's back!

**Comment by samdutton** [comment]
Thanks Hemanth!

**Comment by samdutton** [comment]
Hi @hemanth — getting errors for this again 😢.

**Comment by hemanth** [comment]
@samdutton still seeing the same?

**Comment by samdutton** [comment]
I haven't investigated, but seeing this error:

> Failed to load https://sse.now.sh/: Request header field Cache-Control is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by hemanth** [comment]
@samdutton This [fiddle](https://jsbin.com/qenumuw/edit?html,js,output) works fine.

Maybe something to do with `now` //cc @leo
