### ISSUE TITLE
ClearKey conversion

### ISSUE THREAD

**Issue by techterbium** [samdutton/simpl#117]
Hello @samdutton , please bear me for my newbie question.

Intention: encrypt an mp4 video using webm_crpty using clear key and play it in browser.

I have been following your article [here](https://www.html5rocks.com/en/tutorials/eme/basics/#getting-a-key-from-a-license-server) and encrypted content is created using link [here](https://docs.google.com/document/d/17d6_KX5jX0gY1ygYbjqOEdVzuUGkPO53wL8t40dMGeQ/edit). 

Video details: 
Video type : webm
Codec : VP80

My Question: If I had encrypted the video using the same key as in example (i.e. 0123456789012345), what would be my Uint8Array values?

In your example, it is as below:

`var KEY = new Uint8Array([
  0xeb, 0xdd, 0x62, 0xf1, 0x68, 0x14, 0xd2, 0x7b,
  0x68, 0xef, 0x12, 0x2a, 0xfc, 0xe4, 0xae, 0x3c
]);`

how can I convert 0123456789012345 into something like above? Your help is very much appreciated. Thank you.

**Comment by samdutton** [comment]
Hi @techterbium 

Thanks for the question! 

I haven't worked on EME for a while — I think your best bet is to check out at the demo at [bit.ly/pwa-media](https://bit.ly/pwa-media)), its [source code](https://github.com/GoogleChromeLabs/sample-media-pwa) and the accompanying Developer Diary series.

**Comment by techterbium** [comment]
Hi @samdutton , thank you very much for taking time to reply. 

I know you left **eme** behind you, but I believe, the response that I am looking for is very trivial for you. 

I am trying to replicate your [clearkey example ](https://github.com/samdutton/simpl/tree/gh-pages/eme) with my own encrypted video (which is created using webm_crypt as per [this doc](https://docs.google.com/document/d/17d6_KX5jX0gY1ygYbjqOEdVzuUGkPO53wL8t40dMGeQ/edit)

**I am really having hard time to construct octet sequence array of contents of key file generated out of webm_crypt command.**

Once again, sorry for repeating my question, but I am really helpless here as there is very little support on this subject over internet. Your response might save many hours of mine. please.
