### ISSUE TITLE
cannot initiate webcam for capture of image

### ISSUE THREAD

**Issue by 123AP** [samdutton/simpl#119]
""looking for complete javascript code to access multiple camera drivers"""".

I am trying to use multiple cameras on web application . List of camera drivers should come in the drop down. I should be able to choose required camera driver from the drop down. Based on my selection, i will capture the photo. Whenver i change the drop down option, the corresponding camera driver should open."

CURRENTLY USING RTCMulticonnection for accessing multiple devices *

**Comment by samdutton** [comment]
Not sure which sample you're referring to, but you might want to check out the demos here for camera selection: https://webrtc.github.io/samples.
