### ISSUE TITLE
imageCapture.grabFrame is not a function

### ISSUE THREAD

**Issue by shivangpatel** [samdutton/simpl#121]
Firefox giving me "imageCapture.grabFrame is not a function" error repeatedly during Image capture and it fail to capture image from stream.  But it's working fine with Chrome !

Any suggestions ? 

I am using 
Firefox Quantum
61.0.1(64-bit) on ubuntu 18.04 LTS

**Comment by samdutton** [comment]
Thanks for the heads-up.

AFAIK ImageCapture is still in development on Firefox though it doesn't look like there's been much work recently: https://bugzilla.mozilla.org/show_bug.cgi?id=888177.
