### ISSUE TITLE
MediaRecorder demo is broken by string instead of dict options and mimetypes

### ISSUE THREAD

**Issue by SingingTree** [samdutton/simpl#131]
The [live version](https://simpl.info/mediarecorder/) of the demo is currently broken on Firefox and Chrome I think there's a couple of things going on:
- For the vp8 mime case a dict should be used [here](https://github.com/samdutton/simpl/blob/3cef35a0d5630a0bdb1b210f83c282a60df7ff45/mediarecorder/js/main.js#L136).
- The mime types used should be similar to `video/webm;codecs=vp8`. The VP9 case is rejected on Chrome currently because a comma is used to separate the container from the codecs. The vp8 case should use the same style of string.

**Comment by samdutton** [comment]
Thank you! I'll take a look.

**Comment by SingingTree** [comment]
Thanks! Related commits for posterity: [1](https://github.com/samdutton/simpl/commit/5db479141966e705625afb59aa0a3ee622ac51be), [2](https://github.com/samdutton/simpl/commit/d39bd3b35cb1a96c8cfde7de1c63cac3eb5fe675).

**Comment by samdutton** [comment]
Ah — yes, thanks for adding links to the commits.
