### ISSUE TITLE
Access to incoming live streams?

### ISSUE THREAD

**Issue by QPORIT** [samdutton/simpl#132]
On a chrome browser on Galaxy S6, the demo shows a video feed from front and back cameras. 

If, running simultaneously with this demo, I have a live stream coming in from the VuzeXR to its app, or from the Lenovo Mirage camera to its app,  is it possible to access the live stream from those cameras as a third video feed seen by this demo or an extension of this demo?

What would be necessary, with a live stream from an external camera (like the Vuze XR or Lenovo) to a smartphone, to see that live stream as an additional audio/video feed seen by this demo or some extension of this demo?

Thanks!!!

**Comment by samdutton** [comment]
I haven't been working on media stuff for a while, but have you tried simply calling `getUserMedia()` with multiple video elements, once for each of your devices?

I'm aware of [this](w3c.github.io/mediacapture-main/#implementation-suggestions) but also suggestions that simultaneous streams from multiple devices now works. I guess there might also be some hack with iframes...

(Sorry — haven't got time to try this out right now.)

**Comment by samdutton** [comment]
Haven't had any response for more than a month, so closing.
