### ISSUE TITLE
alpha compatibility of webm files

### ISSUE THREAD

**Issue by The-Linguist** [samdutton/simpl#133]
Fellow coder,
When I view https://simpl.info/videoalpha/ on a SONY phone, both the dancer and the soccer player is displayed correctly.
But when I view the very same page on a HUAWEI phone, the background in the dancer's video is filled with solid gray while only the soccer player's video is displayed correctly.
This suggests that there must be a difference in the way those two files were encoded.
I'm building an educational web application in which I MUST use videos with transparency. I have actually tried converting my alpha containing avi files into webm files with VP8 and VP9 encoding (via Adobe Media Encoder) and tested them on different devices. The problem is, on one device (a SONY phone) only the VP8 version is displayed correctly with a transparent background while on another device (a HUAWEI phone) only the VP9 version is displayed correctly with a transparent background. The phones, in other cases, fill the backgrounds with an undesired solid color.

So far your soccer player's video is THE ONLY video that works on every device that I was able to test it on. And I need to know how that is possible. What are the encoding settings of that one? I would like to know those encoding methods/parameters if possible which also would let everyone know how to get a broader device support.
Thank you for reading.

**Comment by samdutton** [comment]
I haven't really worked on media stuff for a couple of years, but AIUI there's useful stuff in [this thread](https://groups.google.com/a/google.com/forum/#!topic/vpx-eng/SCBdY56KKmw). 

Some links:
• Alpha in WebM [explained](http://wiki.webmproject.org/alpha-channel).
• [Readme for encode wrapper in WebM](https://chromium.googlesource.com/webm/webm-tools/+/master/alpha_encoder/README).

Beyond that, the best place to ask for more information is [webm-discuss](https://groups.google.com/a/webmproject.org/forum/#!forum/webm-discuss).

Hope that's helpful.
