### ISSUE TITLE
i'm find it not work on my anroid mobile default browser

### ISSUE THREAD

**Issue by webxmsj** [samdutton/simpl#135]
i'm find it not work on my anroid mobile default browser

**Comment by samdutton** [comment]
Hi @webxmsj

Thanks for filing an issue.

Which example is not working?

**Comment by webxmsj** [comment]
> Hi @webxmsj
> 
> Thanks for filing an issue.
> 
> Which example is not working?

about getusermedia

**Comment by samdutton** [comment]
I don't think getUserMedia is supported in any version of Android Browser: [caniuse.com/#feat=stream](https://caniuse.com/#feat=stream).

You'll need to use Chrome or another browser that supports getUserMedia.

**Comment by samdutton** [comment]
Haven't heard any more, so closing this.

Feel free to reopen if necessary.

**Comment by jLynx** [comment]
I am having the same issue. it seems Chrome wont give you the current value. it only gives you the value once it changes or has a battery event.

Does anyone know a way to instantly get it?
