### ISSUE TITLE
Not working in safari 12.1.1

### ISSUE THREAD

**Issue by MaheshK02** [samdutton/simpl#139]
i m getting this error while using this code.
error :- navigator.getUserMedia error:Error: Invalid constraint

**Comment by samdutton** [comment]
Thanks for the heads-up. Which example are you getting this error for?

**Comment by MaheshK02** [comment]
example url - https://simpl.info/mediarecorder/

**Comment by samdutton** [comment]
Sadly, MediaRecorder is not supported by Safari on macOS or iOS:
https://caniuse.com/#search=mediarecorder
https://www.chromestatus.com/features/5929649028726784

**Comment by MaheshK02** [comment]
do u know any other way to record video in safari

**Comment by samdutton** [comment]
The WebKit bug for MediaRecorder is [here](https://bugs.webkit.org/show_bug.cgi?id=85851), and you may want to take a look at the article [here](https://blog.addpipe.com/safari-technology-preview-73-adds-limited-mediastream-recorder-api-support/).

Note that MediaRecorder is now an Experimental Feature in Safari in both iOS 12.4 and iOS 13 public beta 4.

There are polyfills such as [this one](https://github.com/ai/audio-recorder-polyfill) for audio, but I don't know of anything for video (see the WebKit bug for reasons why this is difficult).

**Comment by samdutton** [comment]
Closing this issue, but reopen if you need to.
