### ISSUE TITLE
a simple webpage for joining a sports activity

### ISSUE THREAD

**Issue by bindaldhara** [samdutton/simpl#161]

**Comment by samdutton** [comment]
Could you provide more detail about what you're requesting?

**Comment by bindaldhara** [comment]
Using the basics of CSS nd HTML a simple webpage containing a form for joining a sports activity

**Comment by samdutton** [comment]
This site is about individual APIs and platform features: I've tried to
make sure each page only demonstrates one thing at a time.

However, your idea sounds useful. Maybe something you could build on a
different repo :)?

**Comment by bindaldhara** [comment]
Am so srry for this but I didnt get what u r asking from me ..

**Comment by samdutton** [comment]
I just mean that you could build a site of your own that uses basic CSS and
HTML to make a web page for a sports activity.

This site is for examples of single APIs and features.
