### ISSUE TITLE
Note object.observe removal

### ISSUE THREAD

**Issue by ericlaw1979** [samdutton/simpl#168]
- Should this page note that support for the API was removed in Blink?
- If not, should the error that object.observe is undefined be shown in the page itself (vs. requiring user look at the console)?

**Comment by samdutton** [comment]
Thanks for the issue.

I've done a fix — but also reminded that I really need to get someone to take on simpl.info, since I haven't really updated it much in the last couple of years. On balance, I think it's still a useful resource, but it does need to be maintained.
