### ISSUE TITLE
Blob Size getUserMedia

### ISSUE THREAD

**Issue by sikander804** [samdutton/simpl#173]
i have tried recording a 10 to 15 minutes of video after recording my browser stuck , so how much blob size can we record in client side ?

**Comment by samdutton** [comment]
> so how much blob size can we record in client side ?


@beaufortfrancois may know the answer to this.

**Comment by beaufortfrancois** [comment]
https://chromium.googlesource.com/chromium/src/+/main/storage/browser/blob/README.md#blob-storage-limits has all details

**Comment by samdutton** [comment]
Thanks François!

**Comment by sikander804** [comment]
@beaufortfrancois thanks François
