### ISSUE TITLE
Cavas Path Object Example

### ISSUE THREAD

**Issue by zoomclub** [samdutton/simpl#21]
The word is that Chrome Canary has support for the new Canvas Path Object. Looking around I do not yet see a way to utilize this feature. Is it possible to see a demo of Path Objects working on Simpl?

**Comment by samdutton** [comment]
Sorry — just realised I never responded to this!

I don't know of a demo, though I did see this: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_shapes.
