### ISSUE TITLE
Why php?

### ISSUE THREAD

**Issue by hemanth** [samdutton/simpl#30]
I noticed [EventSource#index.php](https://github.com/samdutton/simpl/blob/master/eventsource/index.php)

Is this due to hosting limitation? 

Could we use some node.js like:

``` javascript
var http = require('http');
var sys = require('sys');
var fs = require('fs');

http.createServer(function(req, res) {

  if (req.headers.accept && req.headers.accept == 'text/event-stream') {
    if (req.url == '/events') {
      sendSSE(req, res);
    } else {
      res.writeHead(404);
      res.end();
    }
  } else {
    res.writeHead(200, {'Content-Type': 'text/html'});
    res.write(fs.readFileSync(__dirname + '/index.html'));
    res.end();
  }
}).listen(8000);


function sendSSE(req, res) {
  res.writeHead(200, {
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache',
    'Connection': 'keep-alive'
  });

  var id = (new Date()).toLocaleTimeString();

  setInterval(function() {
    constructSSE(res, id, (new Date()).toLocaleTimeString());
  }, 5000);

  constructSSE(res, id, (new Date()).toLocaleTimeString());
}

function constructSSE(res, id, data) {
  res.write('id: ' + id + '\n');
  res.write("data: " + data + '\n\n');
}
```

**Comment by samdutton** [comment]
OMG — just realised this never got sorted :/.

I've moved simpl.info to GitHub Pages, so not sure how to get this working. (`EventSource` needs a URL on the same origin, right?)

**Comment by hemanth** [comment]
> `EventSource` needs a URL on the same origin, right?

I think with `{ withCredentials: true }` CORS should work fine with the right headers.

BTW the below is the current situation:

<img width="631" alt="screen shot 2016-12-17 at 1 04 30 pm" src="https://cloud.githubusercontent.com/assets/18315/21285258/873dc8bc-c459-11e6-97d8-38d7bf263567.png">

**Comment by samdutton** [comment]
Re origin: [this](https://www.w3.org/TR/2011/WD-eventsource-20110310/) makes it sound like using a different origin is not possible.

**Comment by hemanth** [comment]
Yes was reading the spec, but see this [table](https://developer.mozilla.org/en-US/docs/Web/API/EventSource#Browser_compatibility)

**Comment by samdutton** [comment]
Ah — nice one. Will investigate.
