### ISSUE TITLE
Two mutation events fired?

### ISSUE THREAD

**Issue by shyamsalimkumar** [samdutton/simpl#35]
https://github.com/samdutton/simpl/blob/master/mutationobserver/index.html

We start with `Edit me!` [here](http://www.simpl.info/mutationobserver/) and end up deleting till there is nothing remaining. But on reaching `Edit` (ie. we delete `!`,`e` and `m`)there are two entries although deletion had occurred only once.

```
Old value: Edit
Old value: Edit 
Old value: Edit m
Old value: Edit me
Old value: Edit me!
```

Why?

**Comment by samdutton** [comment]
Thanks for this — just realised I never responded :/.

I don't think this is a problem with the demo. I'd suggest filing a bug if you want: https://developers.google.com/web/feedback
