### ISSUE TITLE
EME: Clear Key example seems broken in current Chrome

### ISSUE THREAD

**Issue by osmestad** [samdutton/simpl#45]
I am not able to get the EME example working in current Chrome (36) on OSX or Win7. Testing Win7 images on BrowserStack.com it works in Chrome 32 but fails in Chrome 33. Any idea what has changed? 
An error of type "webkitkeyerror" appears in the console log. (e.errorCode.code: 1 which seems to mean: MediaKeyError.MEDIA_KEYERR_UNKNOWN )

**Comment by samdutton** [comment]
This has been updated for unprefixed EME.

**Comment by osmestad** [comment]
Thank you :)
