### ISSUE TITLE
EME Error

### ISSUE THREAD

**Issue by saifanam** [samdutton/simpl#46]
I'm getting an InvalidStateError while trying to run the EME example from the latest Chrome (36). This is what appears in the console: Uncaught InvalidStateError: Failed to execute 'endOfStream' on 'MediaSource': The 'updating' attribute is true on one or more of this MediaSource's SourceBuffers.

**Comment by bheller84** [comment]
I can't seem to get the eme/clearkey example to play in my chrome browser ( simpl/eme/clearkey/index.html) The video never starts and image freezes... Does anyone know why?

**Comment by samdutton** [comment]
Apologies for the delay in fixing this – been a bit snowed under with other
projects. Will sort it out soon!

**Comment by samdutton** [comment]
This has been updated for unprefixed EME.
