### ISSUE TITLE
Doesn't work on Firefox

### ISSUE THREAD

**Issue by alexandrevicenzi** [samdutton/simpl#50]
Runnin on Firefox when I press start I get: `ReferenceError: webkitRTCPeerConnection is not defined`

> RTCPeerConnection is currently implemented by Chrome and Opera as webkitRTCPeerConnection and by Firefox as mozRTCPeerConnection (http://www.html5rocks.com/en/tutorials/webrtc/basics/)

**Comment by wnda** [comment]
Maybe I'm simplifying things, but wouldn't it be simple to simply alias the vendor prefixed constructors like this?

    function createRTCPeerConnection(config) {
      if ('RTCPeerConnection' in window) {
        return new RTCPeerConnection(config)
  
      } else if ('webkitRTCPeerConnection' in window) {
        return new webkitRTCPeerConnection(config)
  
      } else if ('mozRTCPeerConnection' in window) {
        return new mozRTCPeerConnection(config)
  
      } else {
        throw new Error('Browser is not supported');
      }
    }

    function createRTCIceCandidate(candidate) {
      if ('RTCIceCandidate' in window) {
        return new RTCPeerConnection(candidate);

      } else if ('webkitRTCIceCandidate' in window) {
        return new webkitRTCPeerConnection(candidate);

      } else if ('mozRTCIceCandidate' in window) {
        return new mozRTCPeerConnection(candidate);

      } else {
        throw new Error('Browser is not supported');
      }
    }

**Comment by samdutton** [comment]
Yeah — it's pretty straightforward :).

Actually the best/right way to do this is probably github.com/webrtc/adapter
.

**Comment by bigt11** [comment]
@wnda I am looking to use this clear key code for video, but as stated above, it does not work on firefox, or IE.  Any examples of the code out there for it to work on all the major browsers?  This seems to only work on chrome.

**Comment by pwa** [comment]
@bigt11 on the road, but just looking into sorting this now.

**Comment by hasse112** [comment]
@wnda @samdutton 
From where would I call the functions (createRTCPeerConnection and createRTCIceCandidate)?
Would you guys mind making a basic example?
