### ISSUE TITLE
Little error on rtcdatachannel

### ISSUE THREAD

**Issue by Snyder** [samdutton/simpl#58]
Hi, i was trying to test the rtcdatachannel but i found that on /js/main.js on lines 19 and 20
```
var dataChannelSend = document.getElementById('#dataChannelSend');
var dataChannelReceive = document.getElementById('#dataChannelReceive');
```
should be
```
var dataChannelSend = document.getElementById('dataChannelSend');
var dataChannelReceive = document.getElementById('dataChannelReceive');
```
Sorry for the trouble, just noticed it, and thanks, i'm starting to develop something and this examples are really useful

**Comment by samdutton** [comment]
Thanks! Not sure how I managed to mess that up... Now fixed.
