### ISSUE TITLE
How to use getSource with Client Application

### ISSUE THREAD

**Issue by KrishPS** [samdutton/simpl#61]
Hi,
I am new to JavaScript. 
I want to get all audio & video source in client application (means without any web server e.g. apache).
I used getSources API to get all devices but it doesn,t work without web-server (apache server).
Could you please guide me how to get all local devices in client application (without any web-server)?

Thanks in Advance.

**Comment by samdutton** [comment]
Hi – you need to run getUserMedia() examples from a server.

It's easy enough to run a server locally with SimpleHTTPServer, or stacks
like MAMP or XAMPP.

Alternatively, run Chrome with flags to enable calling getUserMedia() from
a file:// URL:
stackoverflow.com/questions/13723699/chrome-getusermedia-not-requesting-permission-locally
.

Sam

**Comment by KrishPS** [comment]
Thanks Sam
