### ISSUE TITLE
WebM MSE video stalls after one second in Firefox 42+

### ISSUE THREAD

**Issue by cpeterso** [samdutton/simpl#67]
I reported this bug on Mozilla's Bugzilla but this appears to be a bug in the simpl.info/mse player, not Firefox:

https://bugzilla.mozilla.org/show_bug.cgi?id=1202580

STEPS TO REPRODUCE:
1. Set the following about:config prefs:
`media.mediasource.webm.enabled` = true
`media.mediasource.format-reader.webm` = true
2. Load http://simpl.info/mse/
3. Play the test video if it doesn't start automatically.

RESULT:
In Firefox 42 (Aurora/Dev Edition), the video plays for two seconds then stops. In Firefox 43 (Nightly), the video plays for only one second.

The diagnosis was that this test does not wait for sourceBuffer `updateend` before calling `sourceBuffer.appendBuffer` again. This also fails with mp4. Works ok if `readChunk_(++i);` is called on `updateend`.

**Comment by samdutton** [comment]
Many thanks for this!

Apologies for the crazy delay in responding — I've been snowed under with work this past year :/.

Looks like this is working now in Firefox :).

I'll close the issue, but reopen if you need to.
