### ISSUE TITLE
webm video Clear Key Encryption

### ISSUE THREAD

**Issue by sali141** [samdutton/simpl#71]
Hi Sam,
I have a requirement to encrypt a webm video using clear key encryption and play it as your example below.
http://simpl.info/eme/clearkey/

my question is how to do the encryption. I found below link, but I am not sure where to start from. I am not that good with linux. so please be kind enough to guide me with the steps of webm file encryption with clear key.

https://docs.google.com/document/d/17d6_KX5jX0gY1ygYbjqOEdVzuUGkPO53wL8t40dMGeQ/edit#

**Comment by samdutton** [comment]
Hi — the best advice I can offer is to follow the instructions in the document. You will need Linux! Unfortunately I can't really provide more support here.

There's more information about EME in the HTML5 Rocks article [EME WTF?](https://www.html5rocks.com/en/tutorials/eme/basics/) though this doesn't go into detail about encryption.

You may also want to take a look at [Shaka Player](https://g.co/shakainfo).

**Comment by pradeeprajr93** [comment]
Hey @sali141, I know it's been 2+ years. Just sharing the link, so someone will be helped out!
https://developers.google.com/web/fundamentals/media/manipulating/files#encryption
