### ISSUE TITLE
GUM examples should only use https

### ISSUE THREAD

**Issue by positlabs** [samdutton/simpl#74]
Chrome is enforcing SSL for GUM, so it doesn't work on http anymore.

**Comment by samdutton** [comment]
Thanks.

I want to leave this example as is it, to make it possible for developers to see how browsers respond to an HTTP URL — though I've done something different for the [Media Recorder example](https://simpl.info/mr). 

Having said that, I might add an error message in the page.

**Comment by positlabs** [comment]
+1 for the message. It's an easy detail to overlook.

**Comment by williamboman** [comment]
Would be nice if everything defaulted to https though. Currently;

```sh
$ curl -I https://simpl.info/getusermedia
HTTP/1.1 301 Moved Permanently
...
Location: http://simpl.info/getusermedia/
```

**Comment by samdutton** [comment]
I'd left this to make it possible to test the experience without HTTPS, but
that's just starting to get annoying...

I might get the site to default to HTTPS, as suggested.
