### ISSUE TITLE
Keep displaying 'local ice callback ... ' then it said 'Send channel state is: closed'

### ISSUE THREAD

**Issue by truongnmt** [samdutton/simpl#75]
I'm on Chrome 48.0.2564.116 m
After I press Start, the text field still gray out and 3 button gray out. Open console I see after 'Offer from localPeerConnection ... ' it does 2 loops saying 'local ice callback ... ' then 'Send channel state is: closed'

**Comment by samdutton** [comment]
Sorry for the delay in responding — been too busy at work :/. I see what you mean — I'll take a look.

@KaptenJansson: can you see anything obviously wrong with this (and https://simpl.info/pc, by the looks).

**Comment by KaptenJansson** [comment]
Does this issue even exist anymore on the latest Chrome?

@samdutton You could use adapter.js to ensure better comparability.

Also should probably update .src to srcObject for video elements.

**Comment by samdutton** [comment]
No response to previous comment, so closing.
