### ISSUE TITLE
Problem to alternate camera on android

### ISSUE THREAD

**Issue by marcioamr** [samdutton/simpl#76]
I had some problems to changing camera on my app after an Chrome update.

I solve after change the line above 

```
window.stream.stop();
```

to this:

```
window.stream.getVideoTracks()[0].stop();
```

**Comment by samdutton** [comment]
Thanks for this! I'll update.

**Comment by MrCsabaToth** [comment]
Same thing on Chrome Version 49.0.2623.108 Ubuntu 14.04 (64-bit).
`main.js:48 Uncaught TypeError: window.stream.stop is not a function`

**Comment by samdutton** [comment]
Been snowed under at work — finally got around to fixing this! 

Thanks again.
