### ISSUE TITLE
Linking to files

### ISSUE THREAD

**Issue by adactio** [samdutton/simpl#78]
This is a really great project! I have one little suggestion though...

I think that in some cases (particularly with the JavaScript APIs), it would be better to link through the file listing on GitHub rather than directly to the HTML page on GitHub.

For example, this page on XHR:
http://simpl.info/xhr/

...links through to the corresponding HTML file:
https://github.com/samdutton/simpl/blob/gh-pages/xhr/index.html

...but the really interesting stuff is actually in the associated JavaScript file, so it might make more sense to link to:
https://github.com/samdutton/simpl/tree/gh-pages/xhr

Just my $0.02.

**Comment by samdutton** [comment]
Just realised I never actually responded to this — apologies. I've been snowed under with my day job and haven't been able to do much work on simpl.info recently.

Thank you for your comments!

I completely agree about linking to the relevant file. As a start, I've changed the GitHub links to point to the directory containing the demo, in the commit [here](https://github.com/samdutton/simpl/commit/dc9d8c5e77d340cde6f30d5bddb762b6901ff066).
