### ISSUE TITLE
mapTrack section should be linked from the top page

### ISSUE THREAD

**Issue by dojones1** [samdutton/simpl#79]
I know that it may not be the 'simplest' example, but as it is so epic, you should look to have a link to the mapTrack example code. It is a really good example of using the <track> info to store metadata which can be used in so many other ways, and I haven't seen as good an example anywhere else on the web.

Or maybe add a section for 'awesome examples' to give these not-quite-so-trivial examples a home. Otherwise they are not as visible unless someone happens to know the name of them. (I only found mapTrack after finding the dedicated mapTrack github repository, and trying to make it work - it is out of date now). There is no linkage there to indicate that the 'live' version is now held at simpl.info.

**Comment by samdutton** [comment]
Good point. I've added a link to [simpl.info](https://simpl.info).

Thanks again!
