### ISSUE TITLE
Multiple Webcam Demo is not working on Chrome 

### ISSUE THREAD

**Issue by MortimerNeuss** [samdutton/simpl#83]
I refer to this [demo ](https://simpl.info/getusermedia/sources/) of the repo.
In Chrome 53, two webcams are found, but as soon as I switch to the second webcam, the video-playback-canvas turns black. When I attach the webcams one by the other, they both work. When I connect both, the second never loads the live-image for preview. As the descriptions says: min Chrome 30, it might be that something has changed in the getSource API? Can anyone reproduce this problem?

When the source is changed, JS throws:
`
Uncaught TypeError: window.stream.stop is not a function
GET https://simpl.info/getusermedia/sources/null 
`

sys: Win7, Chrome 53.0.2785.143

**Comment by samdutton** [comment]
Thanks Mortimer! I need to update this.

**Comment by MortimerNeuss** [comment]
Solution [here](https://github.com/samdutton/simpl/issues/76) closed.
