### ISSUE TITLE
Where the video file is stored?

### ISSUE THREAD

**Issue by anildigital** [samdutton/simpl#88]
Hi,

Could you tell where is the video file stored? Is this happening on client side only or a file is stored on server side and then streamed back to client?

**Comment by samdutton** [comment]
For which demo?

**Comment by anildigital** [comment]
@samdutton https://simpl.info/mediarecorder/ After recording, we play the video. I checked the source is blob. But wanted to know whether this file is served from server or browser only. Also where is it getting recorded on browser / server? Thanks.

**Comment by samdutton** [comment]
This file is saved and played back locally.
