### ISSUE TITLE
Imagecapture is not defined

### ISSUE THREAD

**Issue by UtsavAgrawal23** [samdutton/simpl#90]
Hi, I am using chrome version 55,
it shows TypeError: ImageCapture is undefined in both chrome and firefox. i want to capture image and save it in database.But here not able to capture image.

**Comment by samdutton** [comment]
Hi — are you referring to [simpl.info/ic](https://simpl.info/ic)? 

As per the note on the demo, ImageCapture is not implemented in Firefox yet and in Chrome you need to enable Experimental Web Platform features: chrome://flags/#enable-experimental-web-platform-features.

**Comment by UtsavAgrawal23** [comment]
Thanks for info. got it.
