### ISSUE TITLE
question

### ISSUE THREAD

**Issue by vitalygoji** [samdutton/simpl#91]
Sorry for asking here, I don't know were to ask for help. Searches did not help  (
Is there a way to save mediarecorder blob to database and re-display with ajax?
I get ajax jQuery "parserror" when I try to retrieve binary from MySQL.
Thank you guys!

**Comment by samdutton** [comment]
The [MSE example](https://simpl.info/mse/js/main.js) might be able to help you, though that uses the File APIs.
