### ISSUE TITLE
mediaSource.endOfStream() Throws error

### ISSUE THREAD

**Issue by jpmedley** [samdutton/simpl#92]
Line 51 of main.js throws this error on Chrome 55:

Uncaught DOMException: Failed to execute 'endOfStream' on 'MediaSource': The 'updating' attribute is true on one or more of this MediaSource's SourceBuffers.
    at FileReader.reader.onload (https://simpl.info/mse/js/main.js:51:23)

**Comment by samdutton** [comment]
Yeah... need to fix :).

**Comment by wnda** [comment]
I think wrapping `endOfStream()` at L51 in the following way should do it:

    sourceBuffer.addEventListener('updateend', function() {
      if (!sourceBuffer.updating && mediaSource.readyState === 'open') {
        mediaSource.endOfStream();
      }
    });

[**&raquo; Example**](https://rawgit.com/wnda/simpl/gh-pages/mse/)

**Comment by samdutton** [comment]
Nice one @wnda! I've incorporated you fix and it seems to work :).

@joeyparrish — any thoughts on this?

**Comment by joeyparrish** [comment]
I haven't looked at the code in question, but operations on MediaSource and SourceBuffer must be serialized.  Operations on SourceBuffer cannot be started until previous operations on the same buffer are complete (updating==false).  Operations on MediaSource, such as endOfStream or setting duration, must wait until all SourceBuffers are idle.

This is how we ended up with [MediaSourceEngine](https://github.com/google/shaka-player/blob/v2.0.3/lib/media/media_source_engine.js) in Shaka Player, which wraps all the operations in Promises and manages queues of operations.  It makes it much easier to isolate all the events and synchronization between buffers so you can just say "do this" and not worry about MediaSource state in your application.
