### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by vitaliy-bobrov** [samdutton/simpl#97]
As list of examples will grow it'll be handy to have a search field to filter list.

**Comment by samdutton** [comment]
Might be good, but how do you imagine the UI for this?

In other words, what would work better than simply searching for text in the page?

**Comment by vitaliy-bobrov** [comment]
It is more user-friendly I think. Also it will limit text search to only needed area.

**Comment by wnda** [comment]
So, I didn't realise there was discussion about this; last time I checked, #97 was just an open issue, so I thought I'd go ahead make a simple solution:

[&raquo; Demo (may need a hard-refresh if you can't see a search button)](https://rawgit.com/wnda/simpl/gh-pages/index.html)

I've tried to make it perform well.

**Comment by samdutton** [comment]
Thanks @wnda!

I really like what you've done here, and I really appreciate the effort, but I think it's hard to make the 'simple version' worthwhile. Problem is, it can only find stuff in link text, or whatever, and I don't use anything like searchable tags.

I do like the idea of using the GitHub repo search API, though I understand the problems you describe. One option might be simply to add a repo search at the top, which would open a page like https://github.com/samdutton/simpl/search?q=image. Not sure this adds much though.

I'd love to have an organisation for simpl.info (sadly github.com/simpl is taken, and seems to be active) but using a repo for each demo as you say could be overkill :).

**Comment by wnda** [comment]
I understand what you mean. On the homepage, the search thingy I made doesn't really do anything that `ctrl+f` / `⌘+f` can't do faster. 

If used in example pages, I suppose it would save the user from going to home page to navigate from one example to another — but on a fast network the cost of loading the homepage is negligible, and on a slow network the difference between loading the homepage and XHRing the homepage to get the search results is equally negligible.

And as you say, the repo search doesn't add a great deal either.

Not to worry though, I mostly just wanted to make the search widget anyway regardless of whether it would be used or not.

**Comment by samdutton** [comment]
Thanks again @wnda.
